openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://127.0.0.1:8080"
paths:
  /:
    get:
      description: "Hello World!"
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                example1: # 修改示例名称
                  value: "Hello World!"  # 修复示例语法
components: { }  # 如果没有定义 schemas，组件部分可以删除或为空
