version: '3.8'

services:
  nginx:
    image: nginx:1.14.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - kt-scaffold-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: 123123
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - kt-scaffold-network

  app:
    image: kt-scaffold:latest
    ports:
      - "9001:9001"
    depends_on:
      - db
    environment:
      SPRING_PROFILE: dev
    networks:
      - kt-scaffold-network

networks:
  kt-scaffold-network:
    driver: bridge