version: '3.8'

services:
  nginx:
    image: nginx:1.14.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - kt-scaffold-network

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: 123123
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - kt-scaffold-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    expose:
      - "6379"
    volumes:
      - ./redis:/data
    networks:
      - kt-scaffold-network
  app:
    image: kt-scaffold:latest
    ports:
      - "9001:9001"
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      SPRING_PROFILE: dev
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123123
      MYSQL_DB: test
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      SERVE_STATIC: "true"
    volumes:
      - ./config:/config
      - ./logs:/logs
      - ./storage:/storage
    networks:
      - kt-scaffold-network

networks:
  kt-scaffold-network:
    driver: bridge