spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/test
    username: postgres
    password: 123123
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      # password:
      timeout: 10s

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl