spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123123
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          min-idle: 0
          max-active: 8
          max-idle: 8
          max-wait: -1ms
      connect-timeout: 30000ms